name: Tests + Testcafe
# Run unit & integration tests
on: 
  push:
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed
      - '_locales/*.xml'
      - '.vscode/**'
      - 'README_ASSETS/**'
      - 'README.md'

jobs:
  test:
    name: Tests and E2E Tests
    runs-on: ubuntu-latest
    # script uses enviroment vars in unix syntax, windows can not read them
    # macos-latest doesn't work currently: ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.
    strategy:
      fail-fast: false # don't fail fast, because some tests can be flaky so better we get all results
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm ci
      run: |
        npm ci
    - name: npm run build
      run: |
        npm run build
    - name: npm test-unit
      run: |
        npm run test-unit
    - name: prepare testcafe
      working-directory: ./e2e_tests
      env:
        DCC_NEW_TMP_EMAIL: ${{secrets.DCC_NEW_TMP_EMAIL}}
        NODE_ENV: test
        TEST_DIR: .test_tmp_data
      run: |
        npm ci
        xvfb-run --server-args="-screen 0 1280x720x24" npm run start-test
